type: 'python:3.13'
dependencies:
  python3:
    pipenv: "2022.12.19"
    annotated-types==0.7.0
    anyio==4.9.0
    fastapi==0.115.11
    idna==3.10
    pip==24.2
    pydantic==2.10.6
    pydantic-core==2.27.2
    sniffio==1.3.1
    starlette==0.46.1
    typing-extensions==4.12.2


hooks:
  build: |
    set -eu
    pipenv install --system --deploy    
web:
  # Start your app with the configuration you define
  # You can replace the file location with your location
  commands:
    start: uvicorn app.main:app --port 8000 --workers 4
  locations:
    "/":
        passthru: true
    "/static":
        root: "static"
        expires: 1h
        allow: true