version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8080"  # Exponer el puerto 8080 para pruebas locales
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-fastapi-test.cbsk28yuwy1o.us-east-2.rds.amazonaws.com:5432/postgres-fastapi-test
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basedato
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
