# Usar una imagen ligera de Python
FROM python:3.9-slim


# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los requerimientos e instalar dependencias
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

# Copiar el código de la aplicación
COPY ./app .

# Configurar el ENTRYPOINT para tareas específicas
ENTRYPOINT ["alembic"]
CMD ["upgrade", "head"]
