version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:80"  # Exponer el puerto 80 del contenedor en el puerto 8080 de tu máquina
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/basedato
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basedato
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
