"""2d migration

Revision ID: 747d59121c3a
Revises: 0eb86f2bb935
Create Date: 2024-12-17 11:13:05.088953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747d59121c3a'
down_revision: Union[str, None] = '0eb86f2bb935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
