"""insert Roles

Revision ID: a0c8c695ab19
Revises: 747d59121c3a
Create Date: 2024-12-17 11:24:46.462773

"""
from typing import Sequence, Union
from models.rol import Rol
from alembic import op
from database.database import get_db
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c8c695ab19'
down_revision: Union[str, None] = '747d59121c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # connection = op.get_bind()
    # empty_database = connection.execute(sa.text("SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public'")).scalar() == 0
    
    # if empty_database:
    #     # Crear roles predeterminados si la base de datos está vacía
    #     default_roles = [
    #         "Admin",
    #         "SuperAdmin",
    #         "User"
    #     ]

        
    #     for role_data in default_roles:
    #         new_role = Rol(name=role_data)
    #         op.
    #         op.bulk_insert(op.get_bind(), new_role, [
    #             {"name": role_data["name"]}
    #         ])
    # # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
