name: Run Database Migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 920373015494.dkr.ecr.us-east-2.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t fastapi-app . 
        docker tag fastapi-app:latest 920373015494.dkr.ecr.us-east-2.amazonaws.com/fastapi-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push 920373015494.dkr.ecr.us-east-2.amazonaws.com/fastapi-app:latest

    - name: Run migrations
      run: |
        docker run \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          920373015494.dkr.ecr.us-east-2.amazonaws.com/fastapi-app:latest \
          alembic upgrade head
