name: Run Database Migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 920373015494.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t fastapi-app . 
        docker tag fastapi-app:latest 920373015494.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fastapi-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push 920373015494.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fastapi-app:latest

    - name: Run migrations
      run: |
        docker run \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          920373015494.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/fastapi-app:latest \
          alembic upgrade head
